### ISSUE TITLE
how to upload json data ？ And how to add options? 

### ISSUE THREAD

**Issue by Cassine** [dtap-gmbh/refine-java#14]

**Comment by ancore** [comment]
The API is currently being refactored. Please do not use the current version because the next version is structured differently.

**Comment by pranavjadhao** [comment]
@Cassine, did you get the answer for this somehow? If you do then can you please post it here. I am also getting the same problem.

**Comment by ancore** [comment]
This should do it, but it doesn't seem to be accepted by the server. First time I tried JSON and I need to debug.

```java
 try (RefineClient client = RefineClients.create("http://localhost:3333")) {

	 CreateProjectResponse createProjectResponse = RefineCommands
       .createProject()
       .name("Json-Test")
       .file(new File("src/test/resources/addresses.json"))
       .format(UploadFormat.JSON)
       .options(() -> "{ 'encoding': 'UTF-8', 'recordPath': [\"_\", \"_\"]}")
       .execute(client);

}

**Comment by ancore** [comment]
The options are currently expected as a GET parameter in OpenRefine: https://github.com/OpenRefine/OpenRefine/issues/1757

That means the above options are ignored currently as this library uses form parameters.

**Comment by ancore** [comment]
I committed a workaround in refine-java for the options and made a pull request at OpenRefine to fix the bug.
